concourse:
   externalURL: http://concourse-web.concourse.svc.cluster.local:8080

worker:
  replicas: 3
  hardAntiAffinity: true
  resources:
    requests:
      cpu: 500m
      memory: 512Mi

web:
  resources:
    requests:
      cpu: 300m
      memory: 512Mi

persistence:
  worker:
    size: 40Gi