resource_types: ###################################################################################
# https://github.com/zlabjp/kubernetes-resource
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.11"

resources: ########################################################################################

- name: knative-docs-git
  type: git
  source:
    uri: git@github.com:knative/docs.git
    branch: master
    private_key: ((github-private-key))

- name: knative-pipeline-devex-git
  type: git
  source:
    uri: https://github.com/jchesterpivotal/knative-pipeline-devex.git

- name: hello-world-image
  type: docker-image
  source:
    repository: ((hello-world-image-repository))
    username: _json_key
    password: ((gcr-json-key))

- name: gke-cluster
  type: kubernetes
  source:
    server: ((gke-cluster-address))
    token: ((gke-cluster-token))
    certificate_authority: ((gke-cluster-ca))

jobs: #############################################################################################

- name: build-helloworld-ruby-image
  plan:
  - get: knative-docs-git
    trigger: true
    version: every
  - put: hello-world-image
    params:
      build: knative-docs-git/serving/samples/helloworld-ruby

- name: deploy-helloworld-ruby
  plan:
  - get: knative-pipeline-devex-git
  - get: knative-docs-git
    passed: [build-helloworld-ruby-image]
  - get: hello-world-image
    trigger: true
    passed: [build-helloworld-ruby-image]
  - task: edit-service-yaml
    file: knative-pipeline-devex-git/tasks/knative-service-yaml/task.yml
  - put: gke-cluster
    params:
      kubectl: apply -f deployment-yaml/service.yaml
      wait_until_ready: 60
