---
platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu}

inputs:
  - name: knative-pipeline-devex-git
  - name: knative-docs-git

outputs:
  - name: deployment-yaml

run:
  path: knative-pipeline-devex-git/tasks/knative-service-yaml/run
