resource_types: ###################################################################################

- name: knative-service
  type: docker-image
  source:
    repository: gcr.io/cf-elafros-dog/knative-service-resource
    username: _json_key
    password: ((gcp-service-account-json-key))

resources: ########################################################################################

## Git Repos ##

- name: app-git
  type: git
  source:
    uri: https://github.com/jchesterpivotal/knative-pipeline-devex.git
    branch: master

## Images ##

- name: app-image
  type: docker-image
  source:
    repository: ((app-image-repository))
    username: _json_key
    password: ((gcp-service-account-json-key))

## Knative Services ##

- name: knative-service-prod
  type: knative-service
  source:
    name: app-production
    kubernetes_uri: ((gke-cluster-address))
    kubernetes_token: ((gke-cluster-token))
    kubernetes_ca: ((gke-cluster-ca))

jobs: #############################################################################################

- name: build-app-image
  public: true
  plan:
  - get: app-git
    trigger: true
    version: every
  - put: app-image
    params:
      build: app-git/app

- name: deploy-app
  public: true
  plan:
  - get: app-image
    trigger: true
    passed: [build-app-image]
    params:
      skip_download: true
  - put: knative-service-prod
    params:
      image_repository: ((app-image-repository))
      image_digest_path: app-image/digest

- name: react-after-deployment
  public: true
  plan:
  - get: knative-service-prod
    trigger: true
    version: every
    passed: [deploy-app]
  - task: echo-yaml
    config:
      platform: linux
      inputs:
      - name: knative-service-prod
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: cat
        args:
        - knative-service-prod/configuration.yaml

